name: Agile
favicon: null
layout_spectrum: 0.75821
typography_spectrum: 0.74508
title: 'http://sahajsoft.com'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08696069824509323
  lightness: 0.18094672239385545
  saturation: 0.31749772862531245
  rhythmicContrast: 0.5383472952526063
purpose: []
